version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /home/server/.local/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /home/server/.local/www/certbot/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/server/.local/www/certbot/:/var/www/certbot/:rw
      - /home/server/.local/letsencrypt/live/cmrnw.com:/etc/letsencrypt/:rw
  website:
    build: .
    ports:
      - 443:3000
    network_mode: "host"
    volumes:
      - /home/server/.local/letsencrypt/live/cmrnw.com:/etc/letsencrypt/
