version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - $HOME/.local/nginx/conf.d/:./nginx/conf/:ro
      - $HOME/.local/www/certbot/:./certbot/www/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - $HOME/.local/www/certbot/:./certbot/www/:rw
      - $HOME/.local/letsencrypt/:./certbot/conf/:rw
